development:
  adapter: postgresql
  host: localhost
  database: clean_my_city_dev
  username: postgres
  password: pass

test:
  adapter: postgresql
  host: localhost
  database: clean_my_city_test
  pool: 5
  timeout: 5000
  username: postgres
  password: pass

production:
  adapter: postgresql
  database: clean_my_city
  pool: 5
  timeout: 5000
  username: postgres
  password:
